name: publish

on:
    workflow_dispatch:
    push:
      branches:
        - master
        - dev

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: build and write site spa files to www
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: touch www/.nojekyll # to make sure asset paths are correctly identified
        run: "mkdir -p $GITHUB_WORKSPACE/www && touch $GITHUB_WORKSPACE/www/.nojekyll"

      # TODO: For enabling HTTPS on customized GitHub Pages URL
      # - name: generate cname
      #   run: echo "example.com" > "$GITHUB_WORKSPACE/www/CNAME"

      - name: build spa
        uses: logseq/publish-spa@v0.3.1
        # with:
        #   theme_mode: dark

      - name: Deploy to branch publish
        uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: publish
          publish_dir: www
          force_orphan: true

  deploy:
    name: Deploy from branch
    needs: build
    uses: ./.github/workflows/deploy_branch.yaml
    with:
      branch_name: publish
      path: ./
